# **1. Introdução ao Aprendizado de Máquina**

## **Antes de comerçarmos:**

Neste curso, você será exposto a diversos termos expressos em notação matemática. Buscaremos sempre ilustrar de forma intuitiva o significado de cada uma dessas notações. No entanto, para avançar no curso, é fundamental dedicar um tempo para compreendê-las, pois, à medida que os modelos se tornam mais complexos, nem sempre será possível oferecer uma explicação puramente intuitiva.

Se você não está familiarizado com notação matemática ou sente receio ao vê-la, não se preocupe! Pense nela como uma forma compacta de expressar muitas informações em poucas palavras — como uma linguagem própria da matemática. Encare isso como o aprendizado de um novo idioma. 

Boa sorte!

## **O que é Inteligência Artificial?**

Antes de começar com qualquer tipo de conteúdo, é muito importante esclarecer uma coisa: IA NÃO É SÓ CHATGPT!!!

Nos últimos anos, o termo IA tem se tornado uma tendência e é cada vez mais ouvido e repetido por todos os lados. Contudo, apesar de ser amplamente utilizado, são raros os casos em que sua definição é de fato explicitada para o público. Na verdade, chega até mesmo a ser difícil de definir IA com uma explicação simples.

<img src="https://i0.wp.com/cadernopop.com.br/wp-content/uploads/2025/02/robo-selvagem-1024x576.jpg?resize=1024%2C576&ssl=1" height=350>

Inteligência Artificial é um termo muito amplo, que abrange uma vasta gama de estudos em diversas áreas, mas, da maneira mais simples possível, __IA é a capacidade de máquinas simularem a inteligência humana__. Mas o que é a inteligência humana? Bom, somos programadores, não filósofos, mas uma coisa é certa, ela não é algo tão simples de entender ou definir, o que também se aplica à IA.

Da mesma forma como separamos o estudo do corpo humano em diferentes áreas para melhor entendê-lo, assim também fazemos com IA. Dessa forma, algumas das principais subdivisões criadas são:
- Machine Learning
- Deep Learning
- Processamento de linguagem natural (NLP)

Na sequência, traremos uma distinção mais clara sobre alguns desses termos e a IA propriamente dita.

## **Diferenças entre IA, Machine Learning e Deep Learning**

Como dito anteriormente, __IA__ é um campo da ciência da computação que cria sistemas capazes de simular a inteligência humana. Isso inclui desde regras simples baseadas em lógica até sistemas avançados que aprendem com dados. 

Alguns exemplos de IA que podemos ver no dia a dia são:
- Siri 
- Alexa.


__Machine Learning__ por sua vez é uma subárea da Inteligência Artificial. Ela permite que computadores aprendam a partir de dados sem serem explicitamente programados. Em vez de seguir regras fixas, os algoritmos analisam padrões e fazem previsões com base nas informações fornecidas. 

Alguns exemplos de Machine Learning que podemos ver no dia a dia são:
- Algoritmos que recomendam filmes na Netflix
- Sistema de detecção de fraudes em bancos


__Deep Learning__, por fim, é um subconjunto do Machine Learning, que usa redes neurais artificiais profundas para processar dados de forma semelhante ao cérebro humano. Ele é especialmente útil para tarefas que envolvem grandes volumes de dados e reconhecimento de padrões complexos.

Alguns exemplos de Deep Learning que podemos ver no dia a dia são:
- Reconhecimento facial do Facebook
- Carros autônomos da Tesla

De uma maneira geral, podemos entender os três como sendo diferentes partes de um todo, como demonstrado na imagem a seguir:

<img src="https://media.licdn.com/dms/image/v2/C4D12AQFnajkkfJ5ISg/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1608737877258?e=2147483647&v=beta&t=htBCpaT-E02Wzh7dfWnrwcnUca0sDC6FraWgDmwvt14" height=400>

## **Tipos de aprendizado de máquina**

### **O que é o Aprendizado Supervisionado?**

Aprendizado supervisionado é uma técnica de machine learning que usa dados rotulados para treinar algoritmos (mas o que isso quer dizer??). 

Imagine seu professor de cálculo VIII escrevendo tanta letra na lousa que você não sabe se o que ele está fazendo é matemática ou um poema. Ele está assumindo que os alunos entendem tudo o que ele está dizendo (mas todo o mundo sabe que está assumindo errado). Seria muito bom se ele explicasse o significado daquele hieróglifo egípcio, trazendo exemplos com outros exercícios que a gente já conhece e entende. 

E é por isso mesmo que vamos tomar o lugar dele e explicar para o nosso querido aluno (o PC) o que ele precisa entender, trazendo diversos exemplos de exercícios com a resposta correta.

<img src="https://static.wikia.nocookie.net/2a3a4ed5-cece-4538-b323-ef3dbcf09787/scale-to-width/755" height=300/>

Uma vez que ensinamos nosso pupilo, como bons professores que somos, devemos oferecer novos exercícios para ele (sem solução dessa vez), e assim, verificar se agora ele aprendeu e é capaz de fazer por conta própria, apresentando também um feedback apontando seus erros e acertos. Com base nesse feedback, caso o aluno tenha errado boa parte dos exercícios, é hora de chamarmos todos os monitores e fazermos mais outra revisão, possivelmente até mais completa que a primeira. E assim o ciclo pode se repetir algumas vezes até chegarmos a um nível agradável.

Depois de 3 semestres e a um passo de jubilar, o aluno uma hora consegue passar na disciplina. Da mesma forma, após alguns minutos tentando, o nosso modelo está pronto e já é capaz de executar sua tarefa com um certo nível de precisão.

### **O que é o Aprendizado Não Supervisionado**

Se por um lado o aprendizado supervisionado precisa da supervisão humana, o aprendizado não supervisionado não necessita dela.

Nesse caso, imagine que você está vivendo sua vida tranquilamente, curtindo o sítio da dev, e de repente você recebe um e-mail dizendo que seu querido professor de cálculo veio a falecer com seus 136 anos de idade... que tristeza. Se era ruim com ele, o que será de nós sem ele? Nesse caso não teremos mais ninguém para nos dizer a resposta correta dos exercícios para aprendermos antes de testar na prova...

<img src="https://media.tenor.com/gPbkAifeXnkAAAAM/naruto-sad.gif" height=300/>

Mas você não pode ficar de reaval. Sua viagem para o Japão para conhecer o Naruto já está marcada e essa prova vale 8 pontos na média. Você vai passar por bem ou por mal. Dessa forma, você estuda por semanas, até esquece o que é dormir, e enfrenta a prova, dando tudo de si. Apesar dos esforços, você abre a prova e a primeira questão é assombrosa... é um pesadelo. Mas você não se dá por vencido e segue para a próxima, e vê que ela não era tão difícil quanto a primeira. Na verdade nenhuma outra questão é tão difícil quanto a primeira. 

Você faz a prova, ciente de que boa parte das questões está correta, mas a primeira é infernal... não há o que ser feito. Nesse caso, um chute técnico tem mais chances do que uma resposta em branco, e é isso que você faz. Utiliza todo o seu conhecimento adquirido vendo jogadas do Ronaldinho no YouTube e dá o melhor chute de sua vida. 

Com isso você vai tranquilo para o Japão e torce para que o professor não te obrigue a fazer a matéria de novo no próximo semestre (ou no caso, espera que seu código funcione de primeira e você não precise refiná-lo e tentar de novo).

### **O que é o Aprendizado por Reforço?**

Bom dia!!! <br>

Era tudo um sonho! O professor nunca existiu. Na verdade você está em um laboratório e é alvo de testes macabros 💀 <br>

E para piorar a prova é e sempre foi real... <br>

<img src="https://media.tenor.com/M7ec11RfaboAAAAM/waking-up.gif" height=300>

Nesse caso, o estudo tem de continuar, mas dessa vez por conta própria. Serão listas e mais listas de exercícios que devem ser feitas sem ninguém para te ajudar. A única coisa que os cientistas vão fazer para te "apoiar" é te dar um sonho de valsa caso acerte ou uma paulada caso erre o resultado da questão.

Dessa forma, como ninguém aprende assim do nada, nos primeiros dias você leva tanta paulada que fica parecendo o Thanos de tão roxo. Mas na segunda semana, você começa a acertar. Na terceira, mais ainda. Até que chega um momento em que você vai receber tanto sonho de valsa que vai acabar engordando.

O mesmo acontece com a máquina. Quando incentivamos seus acertos e punimos seus erros, também estaremos treinando-o para entregar resultados cada vez mais precisos. Portanto, não tenha medo de dar pauladas nele (só não literalmente por favor. Não nos responsabilizamos por possíveis danos causados aos computadores).

## **Definições iniciais**

### **O que são dados?**

Imagine que você quer entender melhor um grupo de pessoas. 

Para isso, você decide anotar algumas informações sobre cada uma delas, como altura *(em cm)*, peso *(em kg)* e idade *(em anos)*. Você observa uma pessoa e registra esses três valores. Depois, faz o mesmo com outra pessoa e assim por diante.

Cada conjunto de informações que você registra (neste caso, altura, peso e idade) constitui um **dado**, isto é,uma representação de algo do mundo real que queremos estudar ou analisar.

Suponha que coletamos os seguintes dados:

- Pessoa 1: 170cm de altura, 70kg e 25 anos.

- Pessoa 2: 160cm de altura, 55kg e 30 anos.

- Pessoa 3: 180cm de altura, 80kg e 28 anos.

Perceba que, com base nessas três informações podemos representar cada pessoa com três números, veja:

- Pessoa 1 -> (170, 70, 25).

- Pessoa 2 -> (160, 55, 30).

- Pessoa 3 -> (180, 80, 28).
  
Cada linha acima é um conjunto de informações sobre uma pessoa.

**Assim, o conjunto de dados que possuímos é: $$\{(170,70,25),(160,55,30),(180,80,28)\}$$**

### **O que são características?**

Agora, perceba que cada dado é formado por três números diferentes. Cada um deles representa um tipo específico de informação:

- O primeiro número indica a **altura**.

- O segundo número indica o **peso**.

- O terceiro número indica a **idade**.

Chamamos essas informações individuais de **características**. Elas são os aspectos que escolhemos para descrever cada pessoa.

Se tivéssemos escolhido outras informações, como cor dos olhos ou cidade onde mora, teríamos características diferetentes. Assim, **as características são os elementos que compõem cada dado.**

### **O que é um espaço de características?**

Agora que compreendemos que, no exemplo que estamos usando, cada pessoa é caracterizada por três atributos (altura, peso e idade), podemos pensar em um jeito de visualizar essas informações.

Imagine um gráfico em que cada ponto representa uma pessoa, sendo descrita por três características: altura, peso e idade:

- O **eixo X** representa a altura.

- O **eixo Y** representa o peso.

- O **eixo Z** representa a idade.

Cada pessoa pode ser representada por um ponto dentro desse espaço. **Esse espaço, onde todas as combinações possíveis de altura, peso e idade podem existir—isto é, onde essas características podem assumir quaisquer valores dentro de um intervalo permitido—é chamado de espaço de características.**  

Se tivéssemos apenas altura e peso, nosso espaço teria apenas dois eixos, como um gráfico bidimensional. Se adicionássemos mais características, precisaríamos de mais dimensões para representar tudo.

💡 Dica: Tente visualizar esse conceito de forma gráfica: imagine um ponto em um espaço tridimensional, onde o eixo X representa a altura, o eixo Y representa o peso e o eixo Z representa a idade. Esse ponto corresponde a uma pessoa dentro do nosso conjunto de dados. No início, pode parecer desafiador imaginar esse espaço, mas compreender essa ideia tornará o aprendizado muito mais intuitivo no futuro!

### **O que são vetores de características?**

Agora que entendemos que cada pessoa é representada por um ponto dentro do espaço de características, podemos dar um nome especial para essa representação: **vetor de características**

Um vetor de características é simplesmente um conjunto de números que descreve uma pessoa dentro desse espaço. Podemos imaginá-lo como uma "seta" que parte da origem do espaço de características e aponta diretamente para a posição (coordenadas) correspondente a essa pessoa.

Por exemplo, para a Pessoa 1, o vetor de características é $(170, 70, 25)$, o que significa:

- Altura: **170cm**.

- Peso: **70kg**.

- Idade: **25 anos**.

Se pensarmos em um gráfico tridimensional, onde cada eixo representa uma característica (altura, peso e idade), esse vetor nos dá a posição exata da pessoa nesse espaço. A "seta" que parte da origem até esse ponto é uma forma intuitiva de visualizar como cada observação do nosso conjunto de dados pode ser representada matematicamente.

Em resumo, vetor de características é um termo matemático que usamos para representar cada observação dentro do nosso conjunto de dados.

💡 Dica: Realmente tente imaginar que cada pessoa do nosso conjunto de dados é representada por uma seta partindo da origem e apontando para um ponto no espaço tridimensional. Essa seta nada mais é do que o vetor de características, que indica a posição exata da pessoa nesse espaço. No começo, pode ser desafiador visualizar essa ideia, mas pensar nos vetores como "setas direcionadas" ajudará a compreender melhor como os dados são organizados e analisados matematicamente!

## **Formalizando as definições iniciais**

Agora que construímos uma boa intuição, podemos formalizar esses conceitos matematicamente — mantendo o formalismo apenas no nível necessário por enquanto.

### **Dados**

- São um conjunto de observações $X = \{x_{1}, x_{2}, ..., x_{n}\}$, onde cada $x_{i}$ é uma observação.

- No nosso exemplo, os dados são o conjunto de pessoas que analisamos.

### **Características**

- São os atributos que usamos para descrever cada observação. 
  
- Por exemplo, para a observação: $x_{i} = (x_{i1}, x_{i2},...,x_{id})$, cada valor $x_{ij}$ representa um atributo específico da observação $x_{i}$ *(ex: altura, peso, idade)*, onde $j$ varia de $1$ até $d$.

### **Espaço de características**

- É o conjunto de todas as possíveis combinações dos atributos que utilizamos para descrever uma observação.

- Se cada observação é descrita por $d$ características, esse espaço contém todas as combinações possíveis desses $d$ atributos e é matematicamente representado por $R^{d}$.

- Intuitivamente, podemos imaginar esse espaço como um ambiente onde cada observação ocupa uma posição única com base nos valores de suas características.

### **Vetores de características**

- Representam cada observação dentro do espaço de características.

- No nosso exemplo, a **Pessoa 1** é representada pelo vetor: $x_{1} = (170,70,25) \in R^{3}$.

- De forma geral, para um espaço de características com $d$ dimensões, cada observação é um vetor da forma: $x_{i} = (x_{i1},x_{i2},...,x_{id}) \in R^{d}$, onde $i$ indica o número da observação e cada índice $j$ (com $j \in \{1,2,...,d\}$) representa uma característica dessa observação.

### 💡 Dica:

Não se preocupe se essas definições parecerem um pouco abstratas no começo! Você pode continuar avançando no curso sem dominar completamente essas notações matemáticas. No entanto, quanto mais confortável você estiver com essas notações, mais rápido será seu progresso e mais profundo será seu entendimento dos próximos tópicos.

Se algo não ficou claro, pergunte ao responsável pelo case e revise essas definições sempre que for estudar. Criar familiaridade com essas notaçãos ao longo do tempo tornará o aprendizado muito mais natural e intuitivo!

# **2. Fundamentos de Machine Learning**

## **O que é um modelo preditivo?**

Um modelo preditivo é um tipo de modelo de machine learning que tem como objetivo principal fazer previsões sobre novos dados com base em padrões aprendidos a partir de dados históricos.

---

Esses modelos utilizam padrões extraídos dos dados para fazer previsões sobre novas observações. Em termos formais, esses modelos buscam aprender uma função $$f: x_{i} \in X \rightarrow Y$$ que relacione os vetores de características $x_{i} \in X$ com a variável alvo $Y$, de forma que seja possível estimar um $Y$ para um novo $x_{i} \in X$ não observado anteriormente.

---

Os modelos preditivos podem ser utilizados para diferentes tipos de tarefas, como prever se um cliente pagará um empréstimo (classificação), estimar o valor de um imóvel (regressão) ou antecipar o comportamento de uma série temporal (como preços de ativos financeiros).

No entanto, as abordagens para construir esse tipo de modelo variam bastante, dependendo da forma como os dados são tratados e da estratégia utilizada para ajustar os parâmetros do modelo. Podemos dividir os modelos preditivos em algumas categorias principais, são elas:

### **1. Modelos Estatísticos e Probabilísticos**

Esses modelos assumem que os dados seguem uma distribuição probabilística específica e ajustam seus parâmetros para maximizar a verossimilhança dos dados observados.

✅ **Objetivo:** Estimar a distribuição dos dados e inferir a relação entre as variáveis.

**Exemplos:**

- Regressão Linear: Assume que a relação entre as variáveis é linear e que os resíduos seguem uma distribuição normal.

- Regressão Logística: Usa a função sigmoide para modelar probabilidades em problemas de classificação binária.

- Naïve Bayes: Baseia-se na regra de Bayes e assume independência condicional entre os atributos.

📌 **Diferencial:** Esses modelos são baseados em conceitos estatísticos bem definidos e geralmente interpretáveis.

### **2. Modelos Baseados em Otimização**

Esses modelos aprendem a função $f$ otimizando uma métrica específica, sem necessariamente assumir uma distribuição subjacente dos dados.

✅ **Objetivo:** Encontrar um modelo que minimize uma função de erro ou maximize uma margem de separação.

**Exemplos:**

- SVM (Máquinas de Vetores de Suporte): Maximiza a margem entre as classes em problemas de classificação.

- Redes Neurais (MLPs clássicas): Ajustam pesos para minimizar um erro através do gradiente descendente.

📌 **Diferencial:** Baseiam-se em técnicas numéricas de otimização e não exigem uma suposição explícita sobre a distribuição dos dados.

### **3. Modelos Baseados em Particionamento de Dados**

Esses modelos criam regras para dividir os dados em subconjuntos homogêneos, organizando-os hierarquicamente.

✅ **Objetivo:** Criar regras de decisão que segmentem os dados em diferentes categorias.

**Exemplos:**

- Árvores de Decisão: Criam um conjunto de regras sequenciais que levam a decisões.

- Random Forests: Conjunto de árvores de decisão para aumentar a robustez.

📌 **Diferencial:** São fáceis de interpretar e não exigem transformações matemáticas complexas.

### **4. Modelos Baseados em Agrupamento (Clustering)**

Modelos que tentam encontrar padrões e estruturas nos dados sem rótulos supervisionados.

✅ **Objetivo:** Agrupar os dados de forma a maximizar a semelhança dentro dos clusters e minimizar entre os clusters.

**Exemplos:**

- K-Means: Baseado na minimização da soma das distâncias dos pontos ao centro do cluster.

- DBSCAN: Detecta clusters com base na densidade dos dados.

📌 **Diferencial:** Úteis para análise exploratória e segmentação de dados sem supervisão.

### **5. Modelos Baseados em Instâncias**

Esses modelos fazem previsões baseadas nos exemplos mais próximos no conjunto de treinamento, sem construir explicitamente uma função generalizada durante o aprendizado.

✅ **Objetivo:** Utilizar diretamente os dados observados para fazer previsões sem uma fase explícita de aprendizado de parâmetros.

**Exemplo:**
    
- KNN (K-Nearest Neighbors): Classifica ou estima valores com base nos $k$ vizinhos mais próximos.

📌 Diferencial: São conhecidos como modelos preguiçosos (lazy learners) porque não possuem uma fase explícita de treinamento; todo o esforço computacional ocorre no momento da previsão.

### **A importância da amostra de treinamento para um modelo preditivo**

No fim das contas, modelos preditivos tentam encontrar uma função matemática que capture a relação entre as variáveis de entrada (características) e a variável de saída (o que queremos prever). Essa função pode ser vista como uma aproximação da verdadeira relação existente nos dados. No entanto, os dados usados para treinar o modelo representam apenas uma amostra de um conjunto muito maior e desconhecido. Se essa amostra for pequena, enviesada ou não representativa, o modelo pode aprender padrões artificiais que não se repetem em novos dados — um problema conhecido como overfitting.

Diferentes modelos fazem suposições distintas sobre essa relação. Modelos estatísticos assumem que os dados seguem certas distribuições probabilísticas, enquanto modelos baseados em otimização simplesmente ajustam funções para melhor se encaixar nos exemplos observados, sem pressupor uma estrutura fixa. Em ambos os casos, a qualidade da amostra influencia diretamente a capacidade do modelo de fazer boas previsões.

Por isso, ao treinar um modelo, é essencial garantir que os dados de entrada representem bem o fenômeno que estamos tentando modelar. Métodos como validação cruzada, regularização e aumento da diversidade dos dados ajudam a reduzir vieses e melhorar a capacidade do modelo de generalizar para novas situações.

## **Tradeoff entre Bias e Variância**

### **Explicando o Bias**

### **Explicando a Variância**

### **Explicando o Tradeoff entre Bias e Variância**

## **Validação Cruzada e Overfitting**

## **Problemas de classificação**

### **O que é um problema de classificação?**

### **O que é um classificador?**

### **Métricas de Avaliação para Classificação**

#### **Acurácia**

#### **Precisão**

#### **Recall**

#### **F1-Score**

#### **Curva ROC-AUC**

### **O classificador de Bayes**

## **Problemas de regressão**

### **O que é um problema de regressão?**

### **O que é um regressor?**

### **Métricas de Avaliação para Regressão**

#### **MSE**

#### **RMSE**

#### **MAE**

#### **$R^{2}$**

## **Feature Engineering**

# **3. Modelos para Problemas de Classificação**

## **3.1 KNN (K-Nearest-Neighbors)**

## **3.2 Naive Bayes**

## **3.3 Regressão Logística**

### **O que é Regressão Logística?**

### **Interpretação dos coeficientes**

### **Aplicações**

## **3.4 Máquinas de Vetores de Suporte para Classificação (SVC)**

### **O que é Support Vector Classification (SVC)?**

### **Funções kernel (linear, polinomial, radial)**

## **3.5 Árvores de Decisão para Classificação**

### **Conceito de Decision Trees para Classificação**

### **Critérios de divisão**

#### **Critério de Gini**

#### **Entropia**

### **Poda e Overfitting**

## **3.6 Métodos de Ensemble para Classificação**

### **Bagging para Classificação**

### **Boosting para Classificação**

#### **AdaBoost Classifier**

#### **Gradient Boosting Classifier**

#### **Stochastic Gradient Boosting Classifier**

#### **XGBoost Classifier**

### **Stacking para Classificação**

## **3.7 Análise Discriminante**

### **Análise Discriminante Linear (LDA)**

### **Análise Discriminante Quadrática (QDA)**

## **Projeto de Classificação**

**Objetivos:**

1. Comparação entre os modelos

2. Aprender a como escolher o melhor modelo para um problema

...

# **4. Modelos para Problemas de Regressão**

## **4.1 Modelos Lineares para Regressão**

### **Regressão Linear Simples**

O conceito de modelo de Regressão consiste em uma metodologia que estuda a relação entre dois fenômenos, permitindo entender o efeito e a causalidade entre eles, além de prever novos valores. Em outras palavras, seu objetivo é o de traçar um gráfico de linhas entre duas variáveis de dados, x e y.

Ao utilizar de uma Análise de Regressão, o objetivo é identificar um **padrão nos dados**. Dessa forma, busca-se entender o padrão de um valor dependendo de outro ou outros, e assim é possível encontrar uma função que o expressa. Na programação, por exemplo, o conceito de Regressão Linear Simples é utilizado diversas vezes com o intuito de prever dados no futuro a partir de dados históricos. 

Quando há uma relação de um para um, temos nesse caso uma Regressão Linear Simples. Da mesma forma, quando há uma relação de um para muitos, tem-se uma Regressão Linear Múltipla.

<img src="https://images.steamusercontent.com/ugc/2055374171090659544/FF66702C4DB6030EFC56CB823FC7D1F745F40209/?imw=512&&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false" height=300>

Torna-se então necessário definir alguns conceitos importantes:
- **Variável preditora**: é a variável independente, que tem o poder de influenciar na variável que queremos encontrar. Considere como exemplo um caso onde deseja-se entender quais elementos influenciam o preço de uma casa; a variável preditora pode ser o seu tamanho, a quantidade de quartos ou alguma outra informação.
- **Variável alvo ou dependente**: é a variável que queremos prever. No nosso exemplo, será o preço da casa.

Os algoritmos de Regressão Linear, em sua maioria, utilizam um método para calcular tais coeficientes: o Método dos Mínimos Quadrados (MMQ), ou Métodos dos Quadrados Ordinários (MQO) ou ainda, em inglês, Ordinary Least Squares (OLS). Tal método, visa buscar o melhor valor que os coeficientes possam atingir, de maneira que a diferença entre o valor predito pela função e o real, sejam os menores.

Uma vez calculado, o modelo deve ser devidamente avaliado quanto à sua precisão e acurácia. Para isso, existem diversos testes que podem ser realizados:
- **Teste F de Significância global**: afirma se ao menos uma variável do meu modelo está relacionada com a variável alvo. Para isso, o valor-p desta estatística precisa ser menor que 0.05
- **Teste de Significância individuais** ou p-values dos coeficientes: diz o quanto das variáveis preditoras explicam a variável alvo. A métrica padrão é o p-value ser menor que 0.05.
- **Coeficiente R²**: diz o quanto o meu modelo explica seus resultados. É um valor entre 0 e 1. Quanto mais próximo de 1, melhor.

### **Regressão Linear Múltipla**

Como dito anteriormente, a Regressão Linear Múltipla se assemelha em diversos aspectos à Regressão Linear Simples, mas ela, por sua vez, tem como principal, e crucial, distinção, o fato de que **possui mais de um regressor**, ou seja, é necessário que tenha duas ou mais variáveis preditoras.

<img src="https://media.tenor.com/R7wWPCzS9PgAAAAM/shrek-green-lantern.gif" height=300>

Como forma de melhor ilustrar uma regressão em python, traremos agora um exemplo prático de como realizar uma Regressão Linear Múltipla

### **Exemplo Ordem e Regresso**

Trabalharemos com uma base de dados sobre o censo brasileiro de 2022 de forma a tentar identificar alguns padrões e quais fatores afetam aspectos enraizados em nossa sociedade.

Dessa forma, para iniciarmos a análise da base de dados, temos duas etapas iniciais fundamentais as quais, sem elas, seria impossível de realizarmos qualquer tipo de análise de regressão:

- importação das bibliotecas/módulos a serem utilizados
- importação da base de dados

In [108]:
# Importação da biblioteca pandas, fundamental para a manipulação e análise de dados
# Importação do módulo linear_model da biblioteca scikit learn, que será utilizada para a criação do modelo de regressão
import pandas
from sklearn import linear_model

# Importação da base de dados
dados = pandas.read_csv('censo.csv')

#### Banco de bibliotecas - opcional

Caso não tenha alguma das bibliotecas fundamentais para esse exemplo, apenas remova as '#' de cada linha do código abaixo:

In [109]:
# !pip install pandas
# !pip install scikit-learn
# %pip install unidecode

Pronto! A primeira etapa foi concluida. Agora, como uma boa prática do processo de importação de bases de dados, devemos buscar visualizá-los, de forma a verificar se o processo correu como o esperado e se já estamos aptos a iniciar com as análises:

In [110]:
dados.head()

,id_municipio,cor_raca,sexo,grupo_idade,alfabetizacao,populacao
0,1100023,Indígena,Homens,15 a 19 anos,Não alfabetizadas,NaN
1,1100262,Amarela,Mulheres,15 a 19 anos,Não alfabetizadas,NaN
2,1101005,Amarela,Mulheres,15 a 19 anos,Não alfabetizadas,NaN
3,1101435,Amarela,Mulheres,15 a 19 anos,Não alfabetizadas,NaN
4,1101435,Indígena,Mulheres,15 a 19 anos,Não alfabetizadas,NaN

Tudo estava indo bem, até a última coluna mostrar essa que parece ser uma população alienígena. O que é NaN??? E por que temos tantas pessoas diferentes nesse mesmo grupo?

NaN, é um símbolo usado em diversas linguagens de programação para representar um valor numérico indefinido. Isso quer dizer que ele representa um erro na base de dados, ou então um valor ausente. 

Na verdade, existem diversos pontos de atenção dentro dessa base de dados que precisam ser resolvidos antes da análise propriamente dita, mas isso será feito de maneira breve e sem grandes explicações sobre as diferentes etapas uma vez que ela é imprescindível para nosso modelo, contudo não é o foco do nosso exemplo em questão.

In [111]:
from unidecode import unidecode
for col in dados.columns:
    if dados[col].dtype == 'object':
        dados[col] = dados[col].apply(unidecode)
        
dados = dados.dropna()
dados.head()

       id_municipio cor_raca      sexo   grupo_idade  alfabetizacao  populacao
46183       4123501    Parda  Mulheres  15 a 19 anos  Alfabetizadas      256.0
46184       5205513   Branca  Mulheres  15 a 19 anos  Alfabetizadas      256.0
46185       1502707    Preta    Homens  15 a 19 anos  Alfabetizadas      256.0
46186       2703601    Parda    Homens  15 a 19 anos  Alfabetizadas      256.0
46187       2707305   Branca  Mulheres  15 a 19 anos  Alfabetizadas      256.0

Infelizmente, como nem tudo são flores, a base de dados contém diversos dados não numéricos e, como era de se esperar, por se tratar de um modelo matemático, a regressão exige que todos os dados sejam inseridos em formato numérico. Dessa forma, aplicaremos novamente o sklearn em uma etapa de preprocessamento chamada Label Encoder.

Com essa etapa, todos os nossos dados que atualmente estão no formato _object_ serão transformados em numéricos, por meio de divisões em categorias e à atribuição de números que serão utilizados para representar cada uma delas. Por exemplo, na coluna sexo, o LabelEncoder poderá transformar os dados 'Mulheres, Mulheres, Homens' em '1, 1, 0', e assim por diante com essa, e com as demais colunas.

In [112]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for col in dados.columns:
    if dados[col].dtype == 'object':
        dados[col] = label_encoder.fit_transform(dados[col])

Ufa! Agora podemos trabalhar com os dados no formato adequado e dar continuidade na criação do modelo, definindo então quais elementos desejamos escolher como sendo nossas variáveis preditoras e quais serão as dependentes. No nosso exemplo, buscaremos identificar se fatores como raça, sexo e idade impactam na alfabetização dos indivíduos. Dessa forma, definindo nossas variáveis teremos:

In [113]:
# Determinando a variável dependente
y = dados['alfabetizacao']

# Determinando as variáveis independentes
x = dados[['cor_raca', 'sexo', 'grupo_idade']]

# Visualizando as variáveis independentes
x.head()

       cor_raca  sexo  grupo_idade
46183         3     1            0
46184         1     1            0
46185         4     0            0
46186         3     0            0
46187         1     1            0

Agora, adentrando novamente no scikit learn, utilizaremos o método LinearRegression() para criar um objeto de regressão linear. Este objeto tem um método chamado fit() que pega os valores independentes e dependentes como parâmetros e preenche o objeto de regressão com dados que descrevem o relacionamento. Ou seja, é nesta etapa que estaremos de fato aplicando o modelo de regressão aos nossos dados:

In [114]:
regressao = linear_model.LinearRegression()
regressao.fit(x, y)

LinearRegression()

E é isso! Acredite ou não, o modelo já foi criado e está finalizado. Agora ele pode ser utilizado para demais análises estatísticas!

Como dito anteriormente, é interessante que avaliemos a precisão do nosso modelo, e isso pode ser feito de diversas maneiras. Usaremos como teste o R2, a fim de determinar a acurácia do nosso modelo:

In [115]:
significancia_global = regressao.score(x, y)
print(f'Seu modelo tem acurácia de: {significancia_global:.2f}')

Seu modelo tem acurácia de: 0.01

É... mesmo depois de tudo nossa acurácia não chegou nem perto de estar satisfatória...

Mas isso não é raro. Existem diversos fatores que podem inviesar ou afetar nosso modelo como um todo, mas no nosso caso, se pedissem um palpite, diríamos que as variáveis preditoras que utilizamos podem simplesmente não representar impacto algum na nossa variável dependente. Nesse caso, poderíamos tentar uma nova seleção de variáveis, por exemplo, mesmo que menor do que a primeira, o que pode gerar um resultado diferente.

Mas é aqui que a brincadeira começa!!! Ficamos por aqui com a explicação. Chegamos a um resultado, mesmo que não muito satisfatório, de forma que agora cabe a você descobrir formas de melhorar a nossa acurácia! Conto com seus conhecimentos estatísticos, matemáticos e computacionais :)

### **Regressão com Regularização**

#### **Lasso Regression**

#### **Ridge Regression**

## **4.2 Máquinas de Vetores de Suporte para Regressão (SVR)**

### **O que é Support Vector Regression (SVR)?**

### **Aplicação e Hiperparâmetros**

## **4.3 Árvores de Regressão**

### **Conceito de Decision Trees para Regressão**

### **Critérios de divisão**

#### **MSE**

#### **MAE**

### **Poda e Overfitting**

## **4.4 Métodos de Ensemble para Regressão**

### **Bagging para Regressão**

### **Boosting para Regressão**

#### **AdaBoost Regressor**

#### **Gradient Boosting Regressor**

#### **Stochastic Gradient Boosting Regressor**

#### **XGBoost Regressor**

## **Projeto de Regressão**

**Objetivos:**

1. Comparação entre os modelos

2. Aprender a como escolher o melhor modelo para um problema

...

# **5. Aprendizado Não Supervisionado**

# **6. Sistemas de recomendação**